service: compare-backend

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  environment:
    DB_URL: ${self:custom.database.url}

functions:
  googleAuthorizer:
    handler: authorizer.handle
    environment:
      GOOGLE_CLIENT_ID: ${ssm:compare-google-client-id}
  hello:
    handler: handler.get_workspaces
    events:
      - http:
          path: workspaces
          method: get
          authorizer: googleAuthorizer
  postWorkspaces:
    handler: postWorkspaces.create_workspace
    events:
      - http:
          path: workspaces
          method: post
  getWorkspaceById:
    handler: handler.get_workspace_by_id
    events:
      - http:
          path: workspaces/{workspaceId}
          method: get
          authorizer: googleAuthorizer

custom:
  database:
    url: mongodb+srv://${ssm:compare-db-username}:${ssm:compare-db-password}@${ssm:compare-db-url}

plugins:
  - serverless-python-requirements
  - serverless-offline-python
