service: compare-backend

provider:
  name: aws
  runtime: python3.7
  region: us-west-1

functions:
  googleAuthorizer:
    handler: authorizer.handle
    environment:
      GOOGLE_CLIENT_ID: ${ssm:compare-google-client-id}
  hello:
    handler: handler.return_workspaces
    events:
      - http:
          path: workspaces 
          method: get
          authorizer: googleAuthorizer

plugins:
  - serverless-python-requirements
  - serverless-offline-python
